name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: https://index.docker.io/v1/
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    
      - run: |
          docker build -f Dockerfile -t keaaa/jwt-auth:${{ github.sha }} .
          docker tag keaaa/jwt-auth:${{ github.sha }} keaaa/jwt-auth:latest
          docker push keaaa/jwt-auth:${{ github.sha }}
          docker push keaaa/jwt-auth:latest